#!/bin/sh

if [ ! -f /tmp/den ]; then
	if [ -d /etc/apt ]; then
		apt-get update 
		apt-get install -y vim ansible python-pip
		pip install --upgrade ansible
		touch /tmp/den
	else
		yum update
		yum install -y vim ansible python-pip
		pip install --upgrade ansible
		touch /tmp/den	
	fi 
fi
ansible-playbook -i hosts playbook.yml
