---

  - name: create system group
    group: name=webadmin state=present system=yes

  - name: create dir
    file: path=/var/www/vhosts state=directory owner=root group=webadmin mode=0775

  - name: enable module rewrite
    apache2_module: state=present name=rewrite

  - name: enable module rewrite
    apache2_module: state=present name=rewrite
    notified:
      - restart apache   

  - name : dir variable
    set_fact: apache_conf="/etc/httpd/conf/httpd.conf" dir1="/var/www/vhosts/site1/" dir2="/var/www/vhosts/site2/" dir3="/var/www/vhosts/site3/" owner="root" group="webadmin"

  - name: check dir 
    stat: path=/var/www/vhosts/
    register: st
   
  - name: copy dirs
    synchronize: src=templates/apache/ dest=/var/www/vhosts/
    when: st.stat.exists

  - name: ServerAdmin
    replace: dest=/etc/apache2/sites-available/default regexp="^ServerAdmin..*" replace="ServerAdmin admin@trulytech.net" backup=yes

  - name: ServerAdmin ssl
    replace: dest=/etc/apache2/sites-available/default regexp="^ServerAdmin..*" replace="ServerAdmin admin@trulytech.net" backup=yes  
 
  - name: signature 500
    replace: dest=/etc/apache2/conf.d/localized-error-pages regexp="^#ErrorDocument.500..*" replace="ErrorDocument 500 'Internal Server Error'" backup=yes

  - name: Email in signature
    replace: dest=/etc/apache2/conf.d/security regexp="^ServerSignature.On" replace="ServerSignature EMail"

  


#  - name: server-status
#    blockinfile: |
#      dest={{ apache_conf }}
#      marker="# {mark} server-status"
#      content="<Location /server-status>
#               SetHandler server-status
#               Order deny,allow
#               Deny from all
#               Allow from 127.0.0.1 ::1
#               </Location>"
  - name: vhosts1
    blockinfile: |
      dest=/etc/apache2/sites-enabled/vhost1
      marker="# {mark} vhots1"
      content="
                NameVirtualHost *:80
                NameVirtualHost *:443
                <VirtualHost *:80>
                    ServerName site1.23.253.247.72.xip.io
                    DocumentRoot /var/www/vhosts/site1/htdocs
                    ErrorLog /var/www/vhosts/site1/logs/error.log
                    CustomLog /var/www/vhosts/site1/logs/access.log combined
                </VirtualHost>
  - name: vhosts2
    blockinfile: |
      dest=/etc/apache2/sites-enabled/vhost2
      marker="# {mark} vhots2"
      content="              
                <VirtualHost *:80>
                    ServerName site2.23.253.247.72.xip.io
                    ServerAlias www.site2.23.253.247.72.xip.io
                    ServerAlias web.site2.23.253.247.72.xip.io
                    DocumentRoot /var/www/vhosts/site2/htdocs
                    ErrorLog /var/www/vhosts/site2/logs/error.log
                    CustomLog /var/www/vhosts/site2/logs/access.log combined
                    <Directory /var/www/vhosts/site2/htdocs>
                        Options Indexes MultiViews FollowSymLinks
                        AllowOverride All
                        DirectoryIndex index.html index.php
                        Order allow,deny
                        Allow from all
                    </Directory>
                </VirtualHost>
  - name: vhosts3
    blockinfile: |
      dest=/etc/apache2/sites-enabled/vhost3
      marker="# {mark} vhots3"
      content="              
                <VirtualHost *:80>
                    ServerName site3.23.253.247.72.xip.io
                    DocumentRoot /var/www/vhosts/site3/htdocs
                    ErrorLog /var/www/vhosts/site3/logs/error.log
                    CustomLog /var/www/vhosts/site3/logs/access.log combined
                    <Directory /var/www/vhosts/site3/htdocs>
                        AuthType Basic
                        AuthName 'Secure Content'
                        AuthBasicProvider file
                        AuthUserFile /etc/httpd/passwords
                        Require valid-user
                    </Directory>
                </VirtualHost>
                <VirtualHost *:443>
                    SSLEngine on
                    SSLCertificateFile /var/www/vhosts/site3/ssl/ca.crt
                    SSLCertificateKeyFile /var/www/vhosts/site3/ssl/ca.key
                    #SSLCertificateChainFile /etc/apache2/exmaple.crt
                    ServerName site3.23.253.247.72.xip.io
                    DocumentRoot /var/www/vhosts/site3/htdocs
                    ErrorLog /var/www/vhosts/site3/logs/ssl_error.log
                    CustomLog /var/www/vhosts/site3/logs/ssl_access.log common
                </VirtualHost>"
  #- name: vhost
  #  shell: sed -i '/^#..VirtualHost./r templates/apache_centos_vhosts' {{ apache_conf }}
  #- name: htpassword
  #  htpasswd: path=/etc/httpd/passwords crypt_scheme=apr_md5_crypt name=webadmin password=4v2JaLuQ mode=0640
  #- name: create dir document root
  #  file: path={{ dir1 }}htdocs state=directory owner={{ owner }} group={{ group }} mode=0775
  #- name: create dir2 document root
  #  file: path={{ dir2 }}htdocs state=directory owner={{ owner }} group={{ group }} mode=0775
  #- name: create dir3 document root
  #  file: path={{ dir3 }}htdocs state=directory owner={{ owner }} group={{ group }} mode=0775
  #
  #- name: create dir logs
  #  file: path={{ dir1 }}logs state=directory owner={{ owner }} group={{ group }} mode=0775
  #- name: create dir2 document root
  #  file: path={{ dir2 }}logs state=directory owner={{ owner }} group={{ group }} mode=0775
  #- name: create dir3 document root
  #  file: path={{ dir3 }}logs state=directory owner={{ owner }} group={{ group }} mode=0775
  #- name: create dir3 document root
  #  file: path={{ dir3 }}ssl state=directory owner={{ owner }} group={{ group }} mode=0775
  #
  #- name: create logs access
  #  file: path={{ dir1 }}logs/access.log state=file owner={{ owner }} group={{ group }} mode=0775
  #- name: create logs error
  #  file: path={{ dir1 }}logs/error.log state=file owner={{ owner }} group={{ group }} mode=0775
  #- name: create logs access
  #  file: path={{ dir2 }}logs/access.log state=file owner={{ owner }} group={{ group }} mode=0775
  #- name: create logs error
  #  file: path={{ dir2 }}logs/error.log state=file owner={{ owner }} group={{ group }} mode=0775
  #- name: create logs access
  #  file: path={{ dir3 }}logs/access.log state=file owner={{ owner }} group={{ group }} mode=0775
  #- name: create logs error
  #  file: path={{ dir3 }}logs/error.log state=file owner={{ owner }} group={{ group }} mode=0775
  #
  #- name: create logs access ssl
  #  file: path={{ dir3 }}logs/ssl_access.log state=file owner={{ owner }} group={{ group }} mode=0775
  #- name: create logs error ssl
  #  file: path={{ dir3 }}logs/ssl_error.log state=file owner={{ owner }} group={{ group }} mode=0775
