- name: install essential software
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
          - git
          - wget
          - vim
          - curl
          - python
          - python-pip
          - ansible
          - python-passlib

